import { CapacitationCard } from 'components/Capacitation/CapacitationCard';
import { Footer } from 'components/Footer';
// eslint-disable-next-line sort-imports
import Head from 'next/head';
import type { NextPage } from 'next';

const Home: NextPage = () => {
  return (
    <div className="bg-negro-claro">
      <Head>
        <title>Congrats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center mb-16 pt-32">
        <h1 className="font-IBM-Plex-Mono font-semibold text-5xl tracking-widest text-slate-50 text-center mb-44 mt-48">
          Capacitación empresarial
        </h1>
        <div className="space-y-10">
          <CapacitationCard
            technology="NextJs"
            hours="80 horas de curso"
            minimumPeople="Mínimo 3 personas"
            maximumPeople="Máximo 10 personas"
            price="1500 DLS por persona"
          />
          <CapacitationCard
            technology="React"
            hours="40 horas de curso"
            minimumPeople="Mínimo 3 personas"
            maximumPeople="Máximo 10 personas"
            price="800 DLS por persona"
          />

          <CapacitationCard
            technology="React Native"
            hours="50 horas de curso"
            minimumPeople="Mínimo 3 personas"
            maximumPeople="Máximo 10 personas"
            price="1000 DLS por persona"
          />
          <CapacitationCard
            technology="Cypress"
            hours="25 horas de curso"
            minimumPeople="Mínimo 3 personas"
            maximumPeople="Máximo 10 personas"
            price="600 DLS por persona"
          />
        </div>
      </div>
      <div className="text-center">
        <Footer />
      </div>
    </div>
  );
};

export default Home;
