import { Button } from '../components/Button';
import { ConfettiAnimation } from 'components/Congrats/ConfettiAnimation';
import Head from 'next/head';
import type { NextPage } from 'next';
import { useRouter } from 'next/router';

const Home: NextPage = () => {
  const router = useRouter();

  return (
    <div>
      <ConfettiAnimation />
      <Head>
        <title>Congrats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center pt-[400px] space-y-5">
        <h1 className="font-IBM-Plex-Mono font-semibold text-9xl tracking-widest">
          !A aprender!
        </h1>
        <div className="w-72">
          <Button onClick={() => router.push('/lesson')} variant="dark">
            Ir a curso
          </Button>
        </div>
      </div>
    </div>
  );
};

export default Home;
