import { Button } from 'components/Button';
// eslint-disable-next-line sort-imports
import Head from 'next/head';
import { Invoice } from 'components/Invoice/Invoice';
import { NavBar } from 'components/NavBar';
import type { NextPage } from 'next';
import { useUser } from '@supabase/auth-helpers-react';
import { withPageAuth } from '@supabase/auth-helpers-nextjs';

export const getServerSideProps = withPageAuth({ redirectTo: '/' });

const Home: NextPage = () => {
  const user = useUser();

  return (
    <div className="mx-6">
      <Head>
        <title>Invoice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar isLogin />
      <div className="pt-32 flex flex-col items-center w-min mx-auto ">
        <div className="flex w-full justify-between items-center pb-16">
          {user && (
            <p className="font-IBM-Plex-Mono font-bold text-base tracking-widest text-azul-fuerte">
              {user.user_metadata.name}
            </p>
          )}
          <div className="w-52">
            <Button variant="github">Conectar github</Button>
          </div>
        </div>
        <Invoice
          identifier="123456789"
          date="14 de septiembre del 2022"
          street="Hebrea 20"
          delegation="Tlahuac, 13230 CDMX"
          country="México"
          price="140.00"
        />
        <p className="font-IBM-Plex-Sans font-normal text-sm mt-11 mb-32">
          Tienes alguna pregunta, únete a nuestro canal de{' '}
          <a href="#ProximoCanalDeSlack" className="underline cursor-pointer">
            slack
          </a>
        </p>
      </div>
    </div>
  );
};

export default Home;
