import {
  AboutUs,
  Announcement,
  BussinesImages,
  CourseInformation,
  FeaturesSection,
} from '../components/Nextjs';

import { CourseContain } from '../components/Nextjs/Data/CourseContain';
import { ExtraContain } from '../components/Nextjs/Data/ExtraContain';
import { Footer } from '../components/Footer';
// eslint-disable-next-line sort-imports
import Head from 'next/head';
import type { NextPage } from 'next';

const Home: NextPage = () => {
  return (
    <div className="mx-6">
      <Head>
        <title>Sendero</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col items-center pt-32 pb-60">
        <Announcement
          message="¿Buscas capacitación personalizada? Visita nuestra sección"
          link="capacitación empresarial"
        />
        <h1 className="mt-36 font-IBM-Plex-Mono font-semibold text-9xl tracking-widest">
          Aprende Nextjs
        </h1>
        <p className="mt-16 mb-40 font-IBM-Plex-Sans font-normal leading-9 text-2xl tracking-widest w-[810px]">
          Crea aplicaciones en la mitad del tiempo, con nuestro curso
          especializado en Nextjs y crea sistemas robustos, listos para
          producción.
        </p>
        <BussinesImages />
      </div>
      <CourseInformation />
      <FeaturesSection
        nameSection="Que contiene el curso"
        data={CourseContain}
      />

      <FeaturesSection nameSection="Contenido extra" data={ExtraContain} />
      <AboutUs />
      <Footer />
    </div>
  );
};

export default Home;
